name: flutter_habit_tracker
description: A simple habit tracker app (portfolio project).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/splash/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#0B1220"
  image: assets/splash/splash.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#0B1220"
    image: assets/splash/splash.png
